version: "3"
services:
  mongo:
    container_name: mongo_container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    build: .
    image: nodejs-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/nodejs-api/dist
    ports:
      - "8080:8080"
    links:
      - mongo
