version: '3'
services:
  mongo:
    container_name: mongo_container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mongo-express:
    container_name: mongo_express_container
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    links:
      - mongo
  api:
    container_name: api_container
    build: .
    image: nodejs-api
    restart: always
    command: npm start
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - ./dist:/usr/src/nodejs-api/dist
    ports:
      - '${PORT}:${PORT}'
    links:
      - mongo
